baseURL = "https://blog.py4mac.com"
languageCode = "en-us"
title = "py4mac's blog"
theme = "m10c"

[params]
  author = "Pierre-Yves BOISBUNON"
  description = "Machine Learning & IOT "

  [[params.social]]
    name = "github"
    url = "https://github.com/py4mac"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/py4mac"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/pierreyvesboisbunon/"

  [params.style]
    primaryColor = "#001359"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true