site_name: Pierre-Yves BOISBUNON
site_author: py4mac
copyright: "Copyright &copy; 2021 Pierre-Yves BOISBUNON"
site_url: https://py4mac.com
# repo_url: https://github.com/py4mac/py4mac.github.io
# repo_name: py4mac/py4mac.github.io
theme:
  name: material
  language: en
  palette:
    scheme: default
  logo: 'assets/logo.png'
  favicon: 'static/favicon/favicon.ico'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences
  - fontawesome_markdown
  - markdown_include.include:
      base_path: docs
extra_css:
  - "stylesheets/extra.css"
extra_javascript:
  - "https://buttons.github.io/buttons.js"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/py4mac
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/pierreyvesboisbunon
    - icon: fontawesome/brands/medium
      link: https://medium.com/@py4mac