name: Build and Deploy
on:
  push:
    branches:
    - source  # default branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.79.1'
        extended: true
    - name: Build
      run: |
        hugo --minify
    - name: Copy CNAME
      run: |
        cp CNAME ./public/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN  }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
